#!/bin/bash
set -e

cd "$(dirname "$0")/.."
echo "Heres some output"
docker build -t entitlements-gitrepo-auditor-plugin -f spec/acceptance/Dockerfile.entitlements-gitrepo-auditor-plugin .
docker run -w "/data/entitlements" entitlements-gitrepo-auditor-plugin bash -c "script/test"
