name: lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@1d0e911f615a112e322369596f10ee0b95b010ae # pin@v1.183.0
        with:
          bundler-cache: true

      - name: bootstrap
        run: script/bootstrap

      - name: rubocop
        run: bundle exec rubocop -c .rubocop.yml lib/ spec/
