name: lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@e5ac7b085f6e63d49c8973eb0c6e04d876b881f1 # pin@v1.230.0
        with:
          bundler-cache: true

      - name: bootstrap
        run: script/bootstrap

      - name: rubocop
        run: bundle exec rubocop -c .rubocop.yml lib/ spec/
