name: lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@50ba3386b050ad5b97a41fcb81240cbee1d1821f # pin@v1.188.0
        with:
          bundler-cache: true

      - name: bootstrap
        run: script/bootstrap

      - name: rubocop
        run: bundle exec rubocop -c .rubocop.yml lib/ spec/
