name: lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@70da3bbf44ac06db1b0547ce2acc9380a5270d1e # pin@v1.175.0
        with:
          bundler-cache: true

      - name: bootstrap
        run: script/bootstrap

      - name: rubocop
        run: bundle exec rubocop -c .rubocop.yml lib/ spec/
