name: lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@3783f195e29b74ae398d7caca108814bbafde90e # pin@v1.180.1
        with:
          bundler-cache: true

      - name: bootstrap
        run: script/bootstrap

      - name: rubocop
        run: bundle exec rubocop -c .rubocop.yml lib/ spec/
